services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=crustdata'
      - 'POSTGRES_PASSWORD=satish'
      - 'POSTGRES_USER=satish'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5433:5432'